
package com.hxht.autodeploy.webService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZgjkRecordPortType", targetNamespace = "http://ladj.bean.spgl.court.pdcss")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZgjkRecordPortType {


    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ladj.bean.spgl.court.pdcss")
    @RequestWrapper(localName = "getAhAndKtxxByAH", targetNamespace = "http://ladj.bean.spgl.court.pdcss", className = "webService.GetAhAndKtxxByAH")
    @ResponseWrapper(localName = "getAhAndKtxxByAHResponse", targetNamespace = "http://ladj.bean.spgl.court.pdcss", className = "webService.GetAhAndKtxxByAHResponse")
    public String getAhAndKtxxByAH(
        @WebParam(name = "in0", targetNamespace = "http://ladj.bean.spgl.court.pdcss")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://ladj.bean.spgl.court.pdcss")
        String in1);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ladj.bean.spgl.court.pdcss")
    @RequestWrapper(localName = "getCaseSchedule", targetNamespace = "http://ladj.bean.spgl.court.pdcss", className = "webService.GetCaseSchedule")
    @ResponseWrapper(localName = "getCaseScheduleResponse", targetNamespace = "http://ladj.bean.spgl.court.pdcss", className = "webService.GetCaseScheduleResponse")
    public String getCaseSchedule(
        @WebParam(name = "in0", targetNamespace = "http://ladj.bean.spgl.court.pdcss")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://ladj.bean.spgl.court.pdcss")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://ladj.bean.spgl.court.pdcss")
        String in2);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ladj.bean.spgl.court.pdcss")
    @RequestWrapper(localName = "getAhAndKtxx", targetNamespace = "http://ladj.bean.spgl.court.pdcss", className = "webService.GetAhAndKtxx")
    @ResponseWrapper(localName = "getAhAndKtxxResponse", targetNamespace = "http://ladj.bean.spgl.court.pdcss", className = "webService.GetAhAndKtxxResponse")
    public String getAhAndKtxx(
        @WebParam(name = "in0", targetNamespace = "http://ladj.bean.spgl.court.pdcss")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://ladj.bean.spgl.court.pdcss")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://ladj.bean.spgl.court.pdcss")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://ladj.bean.spgl.court.pdcss")
        String in3);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ladj.bean.spgl.court.pdcss")
    @RequestWrapper(localName = "getCode", targetNamespace = "http://ladj.bean.spgl.court.pdcss", className = "webService.GetCode")
    @ResponseWrapper(localName = "getCodeResponse", targetNamespace = "http://ladj.bean.spgl.court.pdcss", className = "webService.GetCodeResponse")
    public String getCode(
        @WebParam(name = "in0", targetNamespace = "http://ladj.bean.spgl.court.pdcss")
        String in0);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ladj.bean.spgl.court.pdcss")
    @RequestWrapper(localName = "userValidate", targetNamespace = "http://ladj.bean.spgl.court.pdcss", className = "webService.UserValidate")
    @ResponseWrapper(localName = "userValidateResponse", targetNamespace = "http://ladj.bean.spgl.court.pdcss", className = "webService.UserValidateResponse")
    public String userValidate(
        @WebParam(name = "in0", targetNamespace = "http://ladj.bean.spgl.court.pdcss")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://ladj.bean.spgl.court.pdcss")
        String in1);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ladj.bean.spgl.court.pdcss")
    @RequestWrapper(localName = "getJcxx", targetNamespace = "http://ladj.bean.spgl.court.pdcss", className = "webService.GetJcxx")
    @ResponseWrapper(localName = "getJcxxResponse", targetNamespace = "http://ladj.bean.spgl.court.pdcss", className = "webService.GetJcxxResponse")
    public String getJcxx(
        @WebParam(name = "in0", targetNamespace = "http://ladj.bean.spgl.court.pdcss")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://ladj.bean.spgl.court.pdcss")
        String in1);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ladj.bean.spgl.court.pdcss")
    @RequestWrapper(localName = "getAhAndKtxxDsrByAH", targetNamespace = "http://ladj.bean.spgl.court.pdcss", className = "webService.GetAhAndKtxxDsrByAH")
    @ResponseWrapper(localName = "getAhAndKtxxDsrByAHResponse", targetNamespace = "http://ladj.bean.spgl.court.pdcss", className = "webService.GetAhAndKtxxDsrByAHResponse")
    public String getAhAndKtxxDsrByAH(
        @WebParam(name = "in0", targetNamespace = "http://ladj.bean.spgl.court.pdcss")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://ladj.bean.spgl.court.pdcss")
        String in1);

}
