
package com.hxht.autodeploy.webService;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZgjkRecord", targetNamespace = "http://ladj.bean.spgl.court.pdcss", wsdlLocation = "http://146.12.2.66:9080/court/services/ZgjkRecord?wsdl")
public class ZgjkRecord
    extends Service
{

    private final static URL ZGJKRECORD_WSDL_LOCATION;
    private final static WebServiceException ZGJKRECORD_EXCEPTION;
    private final static QName ZGJKRECORD_QNAME = new QName("http://ladj.bean.spgl.court.pdcss", "ZgjkRecord");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://146.12.2.66:9080/court/services/ZgjkRecord?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZGJKRECORD_WSDL_LOCATION = url;
        ZGJKRECORD_EXCEPTION = e;
    }

    public ZgjkRecord() {
        super(__getWsdlLocation(), ZGJKRECORD_QNAME);
    }

    public ZgjkRecord(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZGJKRECORD_QNAME, features);
    }

    public ZgjkRecord(URL wsdlLocation) {
        super(wsdlLocation, ZGJKRECORD_QNAME);
    }

    public ZgjkRecord(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZGJKRECORD_QNAME, features);
    }

    public ZgjkRecord(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZgjkRecord(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZgjkRecordPortType
     */
    @WebEndpoint(name = "ZgjkRecordHttpPort")
    public ZgjkRecordPortType getZgjkRecordHttpPort() {
        return super.getPort(new QName("http://ladj.bean.spgl.court.pdcss", "ZgjkRecordHttpPort"), ZgjkRecordPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZgjkRecordPortType
     */
    @WebEndpoint(name = "ZgjkRecordHttpPort")
    public ZgjkRecordPortType getZgjkRecordHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ladj.bean.spgl.court.pdcss", "ZgjkRecordHttpPort"), ZgjkRecordPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZGJKRECORD_EXCEPTION!= null) {
            throw ZGJKRECORD_EXCEPTION;
        }
        return ZGJKRECORD_WSDL_LOCATION;
    }

}
