package com.hxht.autodeploy.sync.rongji.pojo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-01-22T11:31:23.289+08:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://gxjh.court.rjsoft.com/yjwgx/services/ktxx", name = "Export")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Export {

    @WebMethod
    @WebResult(name = "getKtxxReturn", targetNamespace = "http://gxjh.court.rjsoft.com/yjwgx/services/ktxx", partName = "getKtxxReturn")
    public String getKtxx(
            @WebParam(partName = "fjm", name = "fjm")
                    String fjm,
            @WebParam(partName = "sldd", name = "sldd")
                    String sldd,
            @WebParam(partName = "sfgk", name = "sfgk")
                    String sfgk,
            @WebParam(partName = "dsrmc", name = "dsrmc")
                    String dsrmc
    );

    @WebMethod
    @WebResult(name = "saveTsclReturn", targetNamespace = "http://gxjh.court.rjsoft.com/yjwgx/services/ktxx", partName = "saveTsclReturn")
    public String saveTscl2(
            @WebParam(partName = "xmlcontent", name = "xmlcontent")
                    String xmlcontent
    );

    @WebMethod
    @WebResult(name = "saveTsclReturn", targetNamespace = "http://gxjh.court.rjsoft.com/yjwgx/services/ktxx", partName = "saveTsclReturn")
    public String saveTscl(
            @WebParam(partName = "xmlcontent", name = "xmlcontent")
                    String xmlcontent,
            @WebParam(partName = "key", name = "key")
                    String key
    );

    @WebMethod
    @WebResult(name = "getKtxxListReturn", targetNamespace = "http://gxjh.court.rjsoft.com/yjwgx/services/ktxx", partName = "getKtxxListReturn")
    public String getKtxxList(
            @WebParam(partName = "fjm", name = "fjm")
                    String fjm,
            @WebParam(partName = "key", name = "key")
                    String key
    );

    @WebMethod
    @WebResult(name = "queryFtReturn", targetNamespace = "http://gxjh.court.rjsoft.com/yjwgx/services/ktxx", partName = "queryFtReturn")
    public String queryFt(
            @WebParam(partName = "fjm", name = "fjm")
                    String fjm
    );
}
