
package com.hxht.autodeploy.sync.rongji.pojo;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-01-22T11:31:22.600+08:00
 * Generated source version: 3.2.6
 *
 */
public final class Export_ExportImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.sfgl.biz.gxjh.court.rjsoft.com/", "ExportImplService");

    private Export_ExportImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = ExportImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ExportImplService ss = new ExportImplService(wsdlURL, SERVICE_NAME);
        Export port = ss.getExportImplPort();

        {
        System.out.println("Invoking getKtxx...");
        String _getKtxx_fjm = "";
        String _getKtxx_sldd = "";
        String _getKtxx_sfgk = "";
        String _getKtxx_dsrmc = "";
        String _getKtxx__return = port.getKtxx(_getKtxx_fjm, _getKtxx_sldd, _getKtxx_sfgk, _getKtxx_dsrmc);
        System.out.println("getKtxx.result=" + _getKtxx__return);


        }
        {
        System.out.println("Invoking saveTscl2...");
        String _saveTscl2_xmlcontent = "";
        String _saveTscl2__return = port.saveTscl2(_saveTscl2_xmlcontent);
        System.out.println("saveTscl2.result=" + _saveTscl2__return);


        }
        {
        System.out.println("Invoking saveTscl...");
        String _saveTscl_xmlcontent = "";
        String _saveTscl_key = "";
        String _saveTscl__return = port.saveTscl(_saveTscl_xmlcontent, _saveTscl_key);
        System.out.println("saveTscl.result=" + _saveTscl__return);


        }
        {
        System.out.println("Invoking getKtxxList...");
        String _getKtxxList_fjm = "";
        String _getKtxxList_key = "";
        String _getKtxxList__return = port.getKtxxList(_getKtxxList_fjm, _getKtxxList_key);
        System.out.println("getKtxxList.result=" + _getKtxxList__return);


        }
        {
        System.out.println("Invoking queryFt...");
        String _queryFt_fjm = "";
        String _queryFt__return = port.queryFt(_queryFt_fjm);
        System.out.println("queryFt.result=" + _queryFt__return);


        }

        System.exit(0);
    }

}
