package com.hxht.autodeploy.service.sync.huigu;


import com.hxht.autodeploy.service.sync.huigu.pojo.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-08-23T10:34:03.607+08:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://pqWebService.webService.ajgl.withub.net.cn/", name = "PqWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface PqWebService {

    @WebMethod
    @RequestWrapper(localName = "synchroFTInfo", targetNamespace = "http://pqWebService.webService.ajgl.withub.net.cn/", className = "com.hxht.techcrt.service.sync.huigu.pojo.SynchroFTInfo")
    @ResponseWrapper(localName = "synchroFTInfoResponse", targetNamespace = "http://pqWebService.webService.ajgl.withub.net.cn/", className = "com.hxht.techcrt.service.sync.huigu.pojo.SynchroFTInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    String synchroFTInfo(
            @WebParam(name = "xml", targetNamespace = "")
                    String xml
    );

    @WebMethod(operationName = "synchroUserInfo_zgf")
    @RequestWrapper(localName = "synchroUserInfo_zgf", targetNamespace = "http://pqWebService.webService.ajgl.withub.net.cn/", className = "com.hxht.techcrt.service.sync.huigu.pojo.SynchroUserInfoZgf")
    @ResponseWrapper(localName = "synchroUserInfo_zgfResponse", targetNamespace = "http://pqWebService.webService.ajgl.withub.net.cn/", className = "com.hxht.techcrt.service.sync.huigu.pojo.SynchroUserInfoZgfResponse")
    @WebResult(name = "return", targetNamespace = "")
    String synchroUserInfoZgf(
            @WebParam(name = "xml", targetNamespace = "")
                    String xml
    );

    @WebMethod
    @RequestWrapper(localName = "synchroPQInfo", targetNamespace = "http://pqWebService.webService.ajgl.withub.net.cn/", className = "com.hxht.techcrt.service.sync.huigu.pojo.SynchroPQInfo")
    @ResponseWrapper(localName = "synchroPQInfoResponse", targetNamespace = "http://pqWebService.webService.ajgl.withub.net.cn/", className = "com.hxht.techcrt.service.sync.huigu.pojo.SynchroPQInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    String synchroPQInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "synchroDepartment", targetNamespace = "http://pqWebService.webService.ajgl.withub.net.cn/", className = "com.hxht.techcrt.service.sync.huigu.pojo.SynchroDepartment")
    @ResponseWrapper(localName = "synchroDepartmentResponse", targetNamespace = "http://pqWebService.webService.ajgl.withub.net.cn/", className = "com.hxht.techcrt.service.sync.huigu.pojo.SynchroDepartmentResponse")
    @WebResult(name = "return", targetNamespace = "")
    String synchroDepartment(
            @WebParam(name = "xml", targetNamespace = "")
                    String xml
    );

    @WebMethod
    @RequestWrapper(localName = "synchroKtxx", targetNamespace = "http://pqWebService.webService.ajgl.withub.net.cn/", className = "com.hxht.techcrt.service.sync.huigu.pojo.SynchroKtxx")
    @ResponseWrapper(localName = "synchroKtxxResponse", targetNamespace = "http://pqWebService.webService.ajgl.withub.net.cn/", className = "com.hxht.techcrt.service.sync.huigu.pojo.SynchroKtxxResponse")
    @WebResult(name = "return", targetNamespace = "")
    String synchroKtxx(
            @WebParam(name = "xml", targetNamespace = "")
                    String xml
    );

    @WebMethod(operationName = "synchroDepartment_zgf")
    @RequestWrapper(localName = "synchroDepartment_zgf", targetNamespace = "http://pqWebService.webService.ajgl.withub.net.cn/", className = "com.hxht.techcrt.service.sync.huigu.pojo.SynchroDepartmentZgf")
    @ResponseWrapper(localName = "synchroDepartment_zgfResponse", targetNamespace = "http://pqWebService.webService.ajgl.withub.net.cn/", className = "com.hxht.techcrt.service.sync.huigu.pojo.SynchroDepartmentZgfResponse")
    @WebResult(name = "return", targetNamespace = "")
    String synchroDepartmentZgf(
            @WebParam(name = "xml", targetNamespace = "")
                    String xml
    );

    @WebMethod
    @RequestWrapper(localName = "synchroPlayLive", targetNamespace = "http://pqWebService.webService.ajgl.withub.net.cn/", className = "com.hxht.techcrt.service.sync.huigu.pojo.SynchroPlayLive")
    @ResponseWrapper(localName = "synchroPlayLiveResponse", targetNamespace = "http://pqWebService.webService.ajgl.withub.net.cn/", className = "com.hxht.techcrt.service.sync.huigu.pojo.SynchroPlayLiveResponse")
    @WebResult(name = "return", targetNamespace = "")
    String synchroPlayLive(
            @WebParam(name = "xml", targetNamespace = "")
                    String xml
    );

    @WebMethod
    @RequestWrapper(localName = "synchroLyxx", targetNamespace = "http://pqWebService.webService.ajgl.withub.net.cn/", className = "com.hxht.techcrt.service.sync.huigu.pojo.SynchroLyxx")
    @ResponseWrapper(localName = "synchroLyxxResponse", targetNamespace = "http://pqWebService.webService.ajgl.withub.net.cn/", className = "com.hxht.techcrt.service.sync.huigu.pojo.SynchroLyxxResponse")
    @WebResult(name = "return", targetNamespace = "")
    String synchroLyxx(
            @WebParam(name = "xml", targetNamespace = "")
                    String xml
    );

    @WebMethod
    @RequestWrapper(localName = "synchroPQInfoCardId", targetNamespace = "http://pqWebService.webService.ajgl.withub.net.cn/", className = "com.hxht.techcrt.service.sync.huigu.pojo.SynchroPQInfoCardId")
    @ResponseWrapper(localName = "synchroPQInfoCardIdResponse", targetNamespace = "http://pqWebService.webService.ajgl.withub.net.cn/", className = "com.hxht.techcrt.service.sync.huigu.pojo.SynchroPQInfoCardIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String synchroPQInfoCardId(
            @WebParam(name = "xml", targetNamespace = "")
                    String xml
    );

    @WebMethod
    @RequestWrapper(localName = "synchroDepType", targetNamespace = "http://pqWebService.webService.ajgl.withub.net.cn/", className = "com.hxht.techcrt.service.sync.huigu.pojo.SynchroDepType")
    @ResponseWrapper(localName = "synchroDepTypeResponse", targetNamespace = "http://pqWebService.webService.ajgl.withub.net.cn/", className = "com.hxht.techcrt.service.sync.huigu.pojo.SynchroDepTypeResponse")
    @WebResult(name = "return", targetNamespace = "")
    String synchroDepType(
            @WebParam(name = "xml", targetNamespace = "")
                    String xml
    );

    @WebMethod
    @RequestWrapper(localName = "synchroUserInfo", targetNamespace = "http://pqWebService.webService.ajgl.withub.net.cn/", className = "com.hxht.techcrt.service.sync.huigu.pojo.SynchroUserInfo")
    @ResponseWrapper(localName = "synchroUserInfoResponse", targetNamespace = "http://pqWebService.webService.ajgl.withub.net.cn/", className = "com.hxht.techcrt.service.sync.huigu.pojo.SynchroUserInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    String synchroUserInfo(
            @WebParam(name = "xml", targetNamespace = "")
                    String xml
    );

    @WebMethod
    @RequestWrapper(localName = "synchroCaseCode", targetNamespace = "http://pqWebService.webService.ajgl.withub.net.cn/", className = "com.hxht.techcrt.service.sync.huigu.pojo.SynchroCaseCode")
    @ResponseWrapper(localName = "synchroCaseCodeResponse", targetNamespace = "http://pqWebService.webService.ajgl.withub.net.cn/", className = "com.hxht.techcrt.service.sync.huigu.pojo.SynchroCaseCodeResponse")
    @WebResult(name = "return", targetNamespace = "")
    String synchroCaseCode(
            @WebParam(name = "xml", targetNamespace = "")
                    String xml
    );
}
