package com.hxht.autodeploy.sync.huaxia;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2021-01-21T16:46:46.164+08:00
 * Generated source version: 3.1.7
 * 2021.03.19 >>> 自动代理修改rpc daniel
 */
@WebService(targetNamespace = "http://chnsys.com.cn/rcs_ws/", name = "rcsDataInputPortType")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface RcsDataInputPortType {

    @WebMethod(action = "urn:courtRoom")
    @Action(input = "urn:courtRoom", output = "urn:courtRoomResponse")
    @RequestWrapper(localName = "courtRoom", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.CourtRoom")
    @ResponseWrapper(localName = "courtRoomResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.CourtRoomResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String courtRoom(
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(action = "urn:decodeChanelInfo")
    @Action(input = "urn:decodeChanelInfo", output = "urn:decodeChanelInfoResponse")
    @RequestWrapper(localName = "decodeChanelInfo", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.DecodeChanelInfo")
    @ResponseWrapper(localName = "decodeChanelInfoResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.DecodeChanelInfoResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String decodeChanelInfo(
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(operationName = "GetPlKt", action = "urn:GetPlKt")
    @Action(input = "urn:GetPlKt", output = "urn:GetPlKtResponse")
    @RequestWrapper(localName = "GetPlKt", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.GetPlKt")
    @ResponseWrapper(localName = "GetPlKtResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.GetPlKtResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String getPlKt(
            @WebParam(name = "userName", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String userName,
            @WebParam(name = "pwd", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String pwd,
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(operationName = "GetPlAj", action = "urn:GetPlAj")
    @Action(input = "urn:GetPlAj", output = "urn:GetPlAjResponse")
    @RequestWrapper(localName = "GetPlAj", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.GetPlAj")
    @ResponseWrapper(localName = "GetPlAjResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.GetPlAjResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String getPlAj(
            @WebParam(name = "userName", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String userName,
            @WebParam(name = "pwd", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String pwd,
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(action = "urn:deleteTrial")
    @Action(input = "urn:deleteTrial", output = "urn:deleteTrialResponse")
    @RequestWrapper(localName = "deleteTrial", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.DeleteTrial")
    @ResponseWrapper(localName = "deleteTrialResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.DeleteTrialResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String deleteTrial(
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(action = "urn:systemInfo")
    @Action(input = "urn:systemInfo", output = "urn:systemInfoResponse")
    @RequestWrapper(localName = "systemInfo", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.SystemInfo")
    @ResponseWrapper(localName = "systemInfoResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.SystemInfoResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String systemInfo(
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(action = "urn:trialLive")
    @Action(input = "urn:trialLive", output = "urn:trialLiveResponse")
    @RequestWrapper(localName = "trialLive", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.TrialLive")
    @ResponseWrapper(localName = "trialLiveResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.TrialLiveResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String trialLive(
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(action = "urn:trialNote")
    @Action(input = "urn:trialNote", output = "urn:trialNoteResponse")
    @RequestWrapper(localName = "trialNote", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.TrialNote")
    @ResponseWrapper(localName = "trialNoteResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.TrialNoteResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String trialNote(
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(operationName = "GetAjsc", action = "urn:GetAjsc")
    @Action(input = "urn:GetAjsc", output = "urn:GetAjscResponse")
    @RequestWrapper(localName = "GetAjsc", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.GetAjsc")
    @ResponseWrapper(localName = "GetAjscResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.GetAjscResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String getAjsc(
            @WebParam(name = "userName", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String userName,
            @WebParam(name = "pwd", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String pwd,
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(action = "urn:user")
    @Action(input = "urn:user", output = "urn:userResponse")
    @RequestWrapper(localName = "user", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.User")
    @ResponseWrapper(localName = "userResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.UserResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String user(
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(operationName = "GetFt", action = "urn:GetFt")
    @Action(input = "urn:GetFt", output = "urn:GetFtResponse")
    @RequestWrapper(localName = "GetFt", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.GetFt")
    @ResponseWrapper(localName = "GetFtResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.GetFtResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String getFt(
            @WebParam(name = "userName", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String userName,
            @WebParam(name = "pwd", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String pwd,
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(action = "urn:trialRecord")
    @Action(input = "urn:trialRecord", output = "urn:trialRecordResponse")
    @RequestWrapper(localName = "trialRecord", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.TrialRecord")
    @ResponseWrapper(localName = "trialRecordResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.TrialRecordResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String trialRecord(
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(action = "urn:streamServer")
    @Action(input = "urn:streamServer", output = "urn:streamServerResponse")
    @RequestWrapper(localName = "streamServer", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.StreamServer")
    @ResponseWrapper(localName = "streamServerResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.StreamServerResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String streamServer(
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(action = "urn:encode")
    @Action(input = "urn:encode", output = "urn:encodeResponse")
    @RequestWrapper(localName = "encode", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.Encode")
    @ResponseWrapper(localName = "encodeResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.EncodeResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String encode(
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(action = "urn:stoppedTrial")
    @Action(input = "urn:stoppedTrial", output = "urn:stoppedTrialResponse")
    @RequestWrapper(localName = "stoppedTrial", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.StoppedTrial")
    @ResponseWrapper(localName = "stoppedTrialResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.StoppedTrialResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String stoppedTrial(
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(operationName = "SendKtxx", action = "urn:SendKtxx")
    @Action(input = "urn:SendKtxx", output = "urn:SendKtxxResponse")
    @RequestWrapper(localName = "SendKtxx", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.SendKtxx")
    @ResponseWrapper(localName = "SendKtxxResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.SendKtxxResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String sendKtxx(
            @WebParam(name = "userName", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String userName,
            @WebParam(name = "pwd", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String pwd,
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(operationName = "GetDsr", action = "urn:GetDsr")
    @Action(input = "urn:GetDsr", output = "urn:GetDsrResponse")
    @RequestWrapper(localName = "GetDsr", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.GetDsr")
    @ResponseWrapper(localName = "GetDsrResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.GetDsrResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String getDsr(
            @WebParam(name = "userName", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String userName,
            @WebParam(name = "pwd", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String pwd,
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(action = "urn:resumeTrial")
    @Action(input = "urn:resumeTrial", output = "urn:resumeTrialResponse")
    @RequestWrapper(localName = "resumeTrial", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.ResumeTrial")
    @ResponseWrapper(localName = "resumeTrialResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.ResumeTrialResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String resumeTrial(
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(action = "urn:startedTrial")
    @Action(input = "urn:startedTrial", output = "urn:startedTrialResponse")
    @RequestWrapper(localName = "startedTrial", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.StartedTrial")
    @ResponseWrapper(localName = "startedTrialResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.StartedTrialResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String startedTrial(
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(operationName = "GetRy", action = "urn:GetRy")
    @Action(input = "urn:GetRy", output = "urn:GetRyResponse")
    @RequestWrapper(localName = "GetRy", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.GetRy")
    @ResponseWrapper(localName = "GetRyResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.GetRyResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String getRy(
            @WebParam(name = "userName", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String userName,
            @WebParam(name = "pwd", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String pwd,
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(action = "urn:trialPublish")
    @Action(input = "urn:trialPublish", output = "urn:trialPublishResponse")
    @RequestWrapper(localName = "trialPublish", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.TrialPublish")
    @ResponseWrapper(localName = "trialPublishResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.TrialPublishResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String trialPublish(
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(action = "urn:decode")
    @Action(input = "urn:decode", output = "urn:decodeResponse")
    @RequestWrapper(localName = "decode", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.Decode")
    @ResponseWrapper(localName = "decodeResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.DecodeResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String decode(
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(operationName = "GetZzjg", action = "urn:GetZzjg")
    @Action(input = "urn:GetZzjg", output = "urn:GetZzjgResponse")
    @RequestWrapper(localName = "GetZzjg", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.GetZzjg")
    @ResponseWrapper(localName = "GetZzjgResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.GetZzjgResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String getZzjg(
            @WebParam(name = "userName", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String userName,
            @WebParam(name = "pwd", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String pwd,
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(action = "urn:pauseTrial")
    @Action(input = "urn:pauseTrial", output = "urn:pauseTrialResponse")
    @RequestWrapper(localName = "pauseTrial", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.PauseTrial")
    @ResponseWrapper(localName = "pauseTrialResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.PauseTrialResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String pauseTrial(
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(operationName = "GetPqsc", action = "urn:GetPqsc")
    @Action(input = "urn:GetPqsc", output = "urn:GetPqscResponse")
    @RequestWrapper(localName = "GetPqsc", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.GetPqsc")
    @ResponseWrapper(localName = "GetPqscResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.GetPqscResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String getPqsc(
            @WebParam(name = "userName", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String userName,
            @WebParam(name = "pwd", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String pwd,
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(action = "urn:setWorkerClassMap")
    @Action(input = "urn:setWorkerClassMap")
    @Oneway
    @RequestWrapper(localName = "setWorkerClassMap", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.SetWorkerClassMap")
    void setWorkerClassMap(
            @WebParam(name = "workerClassMap", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    Object workerClassMap
    );

    @WebMethod(action = "urn:deleteCase")
    @Action(input = "urn:deleteCase", output = "urn:deleteCaseResponse")
    @RequestWrapper(localName = "deleteCase", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.DeleteCase")
    @ResponseWrapper(localName = "deleteCaseResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.DeleteCaseResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String deleteCase(
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );

    @WebMethod(action = "urn:department")
    @Action(input = "urn:department", output = "urn:departmentResponse")
    @RequestWrapper(localName = "department", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.Department")
    @ResponseWrapper(localName = "departmentResponse", targetNamespace = "http://chnsys.com.cn/rcs_ws/", className = "cn.com.chnsys.rcs_ws.DepartmentResponse")
    @WebResult(name = "return", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
    String department(
            @WebParam(name = "protocolXml", targetNamespace = "http://chnsys.com.cn/rcs_ws/")
                    String protocolXml
    );
}
