---
grails:
  profile: web
  codegen:
    defaultPackage: autodeploy
  gorm:
    reactor:
      # Whether to translate GORM events into Reactor events
      # Disabled by default for performance reasons
      events: false
info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
spring:
  main:
    banner-mode: "off"
  groovy:
    template:
      check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
  enabled: false
  jmx:
    enabled: true

---
grails:
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: singleton
    upload:
      maxFileSize: 2147483648
      maxRequestSize: 300000000
  converters:
    encoding: UTF-8
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlets: html
        taglib: none
        staticparts: none
endpoints:
  jmx:
    unique-names: true

---
#数据库相关配置
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
dataSource:
  pooled: true
  jmxExport: true
  driverClassName: com.mysql.jdbc.Driver
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  username: root
  password: dcs2011

environments:
  development:
    dataSource:
      dbCreate: update
      url: jdbc:mysql://192.168.0.203:3306/autodeploy?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true
  test:
    dataSource:
      dbCreate: update
      url: jdbc:mysql://192.168.0.203:3306/autodeploy?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true
  production:
    dataSource:
      dbCreate: update
      url: jdbc:mysql://192.168.0.203:3306/autodeploy?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
---
grails:
  corss:
    enabled: true
  plugin:
    console:
      enabled: true
    springsecurity:
      userLookup:
        usernamePropertyName: username
        userDomainClassName: com.hxht.autodeploy.manager.authority.User
        authorityJoinClassName: com.hxht.autodeploy.manager.authority.UserRole
      authority:
        className: com.hxht.autodeploy.manager.authority.Role
      logout:
        postOnly: false
      auth:
        loginFormUrl: /login/auth
      providerNames:
        - tcAuthenticationProvider
        - anonymousAuthenticationProvider
        - rememberMeAuthenticationProvider
      securityConfigType: InterceptUrlMap
      interceptUrlMap: [
        { pattern: '/**/favicon.ico',            access: [ 'permitAll' ] },
        { pattern: '/error',                     access: [ 'permitAll' ] },
        { pattern: '/authority',                 access: [ 'permitAll' ] },
        { pattern: '/assets/**',                 access: [ 'permitAll' ] },
        { pattern: '/login/**',                  access: [ 'permitAll' ] },
        { pattern: '/logout/**',                 access: [ 'permitAll' ] },
        { pattern: '/console/**',                access: [ 'permitAll' ] },
        { pattern: '/static/console/**',         access: [ 'permitAll' ] },
        { pattern: '/**',                        access: [ 'ROLE_SUPER','ROLE_/','ROLE_ADMIN' ] }
      ]

---
tc:
  version: ---- autodeploy version 1.0.0 build 20210730 ----

server:
  servlet:
    session:
      timeout: 7200
  contextPath: '/auto'
  port: 80

jwt:
  info:
    secret: XXXXX
    expires: 86400000
    tokenExclude: /api/token